import { Decision } from '@/types/decision';

// Generate structured Markdown representation of the recommendation
export function generateMarkdownReport(decision: Decision): string {
  if (!decision.result) return 'No recommendation generated yet.';

  const r = decision.result;
  const prosConsMd = Object.keys(r.pros).map(opt => {
    const pros = r.pros[opt]?.map(p => `  * ${p}`).join('\n') || '';
    const cons = r.cons[opt]?.map(c => `  * ${c}`).join('\n') || '';
    return `### Option: ${opt}\n**Pros:**\n${pros}\n\n**Cons:**\n${cons}`;
  }).join('\n\n');

  const matrixMd = r.matrix.rows.map(row => {
    const scores = Object.entries(row.scores).map(([k, v]) => `  * ${k}: ${v}/10`).join('\n');
    return `* **${row.name}** (Overall Score: ${row.overallScore}%)\n${scores}`;
  }).join('\n');

  return `
# DecisionPilot AI Report

**Decision Category:** ${decision.category}
**Original Question:** ${decision.question}
**Date Generated:** ${new Date(decision.updatedAt).toLocaleDateString()}

---

## Executive Summary
${r.summary}

## Recommendation
**Recommended Choice:** ${r.recommendedOption}
**Confidence Level:** ${r.confidence.score} (${r.confidence.reason})

---

## Reasoning & Key Factors
${r.reasoning.map(line => `* ${line}`).join('\n')}

---

## Decision Matrix Ratings
${matrixMd}

---

## Trade-off Summary
${r.tradeOffs}

## Critical Risks & Pitfalls
${r.hiddenRisks.map(risk => `* ${risk}`).join('\n')}

## Long-term Impact (2-5 years)
${r.longTermImpact}

---

## Assumptions Made
${r.assumptions.map(ass => `* ${ass}`).join('\n')}

## Next Recommended Actions
${r.nextActions.map(act => `* ${act}`).join('\n')}

*Generated by DecisionPilot AI — Make structured decisions instead of guesses.*
`.trim();
}

// Copy report text to clipboard
export async function copyReportToClipboard(decision: Decision): Promise<boolean> {
  const text = generateMarkdownReport(decision);
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.error('Clipboard copy failed', err);
    return false;
  }
}

// Share decision summary
export function shareDecision(decision: Decision): { success: boolean; url?: string } {
  if (typeof window === 'undefined') return { success: false };
  try {
    const shareUrl = `${window.location.origin}/?share=${decision.id}`;
    // In a live production app, we would write this URL. We'll copy to clipboard or use navigator.share if supported
    if (navigator.share) {
      navigator.share({
        title: `DecisionPilot AI Report: ${decision.title}`,
        text: `Check out this decision recommendation: ${decision.result?.recommendedOption}`,
        url: shareUrl
      }).catch(err => console.log('Share canceled', err));
      return { success: true };
    }
    return { success: false, url: shareUrl };
  } catch {
    return { success: false };
  }
}

// Trigger Print to PDF window
export function exportToPdf(): void {
  if (typeof window !== 'undefined') {
    window.print();
  }
}
